---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: no
  parallel: true
  default_box: 'generic/centos9s'
platforms:
  - name: crc
    memory: 16384
    cpus: 4
    provider_options:
      cpu_mode: 'host-passthrough'
      nested: true
      machine_type: 'q35'
    groups:
      - openshift
  - name: compute
    memory: 2048
    cpus: 2
    provider_options:
      cpu_mode: 'host-passthrough'
      nested: true
      machine_type: 'q35'
    groups:
      - openstack
provisioner:
  name: ansible
verifier:
  name: ansible
